"""empty message

Revision ID: 04e8715cf4ee
Revises: e478c0bc9dcd
Create Date: 2021-11-03 01:01:42.583186

"""

# revision identifiers, used by Alembic.
revision = '04e8715cf4ee'
down_revision = 'e478c0bc9dcd'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('motivos', sa.Column('page', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('motivos', 'page')
    # ### end Alembic commands ###
