"""empty message

Revision ID: 52b2b68a6fec
Revises: 04e8715cf4ee
Create Date: 2021-11-12 15:29:14.831141

"""

# revision identifiers, used by Alembic.
revision = '52b2b68a6fec'
down_revision = '04e8715cf4ee'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('motivos', sa.Column('exemplo', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('motivos', 'exemplo')
    # ### end Alembic commands ###
